### ISSUE TITLE
Upgrade Build Tools to Babel 7 and webpack 4

### ISSUE THREAD

**Issue by reggaemuffin** [BuildTeamDev/steem-editor#1]
We should keep up with new versions of our build tools.

Babel 7 has renamed packages and breaking changes we should consider:

https://babeljs.io/docs/en/v7-migration

Webpack 4 has a new structure for how plugins work and we can integrate improved post processing plugins to improve our bundle size even further

**Comment by Vheissu** [comment]
@reggaemuffin The changes have been made and a pull request submitted here: https://github.com/BuildTeamDev/steem-editor/pull/2
